# Config for https://github.com/apps/release-drafter
template: |
  ## TODO: Added/Removed/Fixed/Changed

  $CHANGES

  ## Upgrading

  To upgrade, update your `pipeline.yml` files:

  ```diff
  steps:
    - command: test.sh
      plugins:
  -     shellcheck#$PREVIOUS_TAG:
  +     shellcheck#TODO:
          files: scripts/*.sh
  ```
