name: Shellcheck
description: Run shellcheck over your shell scripts
author: https://github.com/lox
requirements:
  - bash
  - docker
configuration:
  properties:
    globstar:
      type: boolean
      default: false
    extglob:
      type: boolean
      default: false
    files:
      type: [string, array]
      minItems: 1
    options:
      type: [string, array]
      minItems: 1
    version:
      type: [string]
  required:
    - files
