steps:
  - label: run bats tests
    plugins:
      - docker-compose#v3.0.0:
          run: tests

  - label: run shellcheck
    plugins:
      - shellcheck#${BUILDKITE_COMMIT}:
          files:
            - hooks/*
            - buildkite/*.sh

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v2.0.0:
          id: shellcheck
