steps:
  - label: run bats tests
    plugins:
      - plugin-tester#v1.2.0: ~

  - label: run shellcheck
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/*
            - buildkite/*.sh

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: shellcheck

  - label: selftest - fork
    plugins:
      - ${BUILDKITE_PULL_REQUEST_REPO}#${BUILDKITE_COMMIT}:
          files:
            - hooks/*
            - buildkite/*.sh
    if: build.pull_request.repository.fork == true

  - label: selftest
    plugins:
      - shellcheck#${BUILDKITE_COMMIT}:
          files:
            - hooks/*
            - buildkite/*.sh
    if: build.pull_request.repository.fork == false

  - label: "Security Scan"
    key: security_scan
    plugins:
      - secrets#v1.0.1:
          variables:
            GITHUB_TOKEN: GITHUB_TOKEN
      - ossf-scorecard#v1.0.1:
          github_token: $$GITHUB_TOKEN
