steps:
  - label: run bats tests
    plugins:
      docker-compose#v2.6.0:
        run: tests

  - label: run shellcheck
    plugins:
      shellcheck#${BUILDKITE_COMMIT}:
        files:
          - hooks/*
          - buildkite/*.sh

  - label: ":sparkles: lint"
    plugins:
      plugin-linter#v1.0.0:
        name: shellcheck