steps:
  - label: run bats tests
    plugins:
      - plugin-tester#v1.1.0: ~

  - label: run shellcheck
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/*
            - buildkite/*.sh

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.2.0:
          id: shellcheck

  - label: selftest
    plugins:
      - shellcheck#${BUILDKITE_COMMIT}:
          files:
            - hooks/*
            - buildkite/*.sh
