#!/bin/bash
set -eu -o pipefail

# Reads either a value or a list from plugin config
function plugin_read_list() {
  local prefix="BUILDKITE_PLUGIN_SHELLCHECK_$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

IFS=$'\n\t'
files=()

# Evaluate all the globs and return the files that exist
for file in $(plugin_read_list FILES) ; do
  if [[ -e $file ]] ; then
    files+=("$file")
  fi
done

if [[ -z ${files:-} ]] ; then
  echo "No files found to shellcheck"
  exit 1
fi

# Read in the options to pass to shellcheck.  Ask for color by default
# for pretty online log display (but someone can override this with an
# explicit `options: "--color=never"`)
options=("--color=always")
while IFS=$'\n' read -r option ; do
  options+=("$option")
done < <(plugin_read_list OPTIONS)

BUILDKITE_PLUGIN_SHELLCHECK_VERSION="${BUILDKITE_PLUGIN_SHELLCHECK_VERSION:-stable}"

echo "+++ Running shellcheck on ${#files[@]} files"
if docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "koalaman/shellcheck:$BUILDKITE_PLUGIN_SHELLCHECK_VERSION" "${options[@]+${options[@]}}" "${files[@]}" ; then
  echo "Files are ok ✅"
else
  exit 1
fi
